// Design tokens – colors for light/dark themes
// Migrated from drawing-app/constants/Colors.js

export const colors = {
  light: {
    text: '#11181C',
    background: '#FFFFFF',
    navBackground: '#F5F5F5',
    dropdownBackground: '#FAFAFA',
    actionButton: '#4A90D9',
    actionButtonHover: '#357ABD',
    stopButton: '#D94A4A',
    icon: '#687076',
    iconHover: '#11181C',
    headerIcon: '#11181C',
    canvasBackground: '#FFFFFF',
    svgStrokeColor: '#000000',
    landmarkPointsLeft: '#4A90D9',
    landmarkPointsRight: '#8B5CF6',
    landmarkPointsCenter: '#EAB308',
    landmarkConnectors: '#6B7280',
    listItemBackground: '#F5F5F5',
    listItemBackgroundHover: '#E8E8E8',
  },
  dark: {
    text: '#ECEDEE',
    background: '#0A0A0A',
    navBackground: '#1A1A1A',
    dropdownBackground: '#1F1F1F',
    actionButton: '#4A90D9',
    actionButtonHover: '#5BA0E9',
    stopButton: '#D94A4A',
    icon: '#9BA1A6',
    iconHover: '#ECEDEE',
    headerIcon: '#ECEDEE',
    canvasBackground: '#1A1A1A',
    svgStrokeColor: '#FFFFFF',
    landmarkPointsLeft: '#4A90D9',
    landmarkPointsRight: '#8B5CF6',
    landmarkPointsCenter: '#EAB308',
    landmarkConnectors: '#6B7280',
    listItemBackground: '#1A1A1A',
    listItemBackgroundHover: '#2A2A2A',
  },
} as const;
